### ISSUE TITLE
Pen Test: Sensitive Files readable/writeable by Anyone

### ISSUE THREAD

**Issue by apurvam** [responsivedev/responsive-pub#198]

**Comment by rodesai** [comment]
#203 sets read-only permissions for the secrets volume, so it should not be writable from the container.

**Comment by rodesai** [comment]
We are setting the volume's permissions to read-only:
```
      volumeMounts:
      - mountPath: /etc/responsive-operator/
        name: cfg
        readOnly: true
...
    volumes:
    - name: cfg
      secret:
        defaultMode: 292
        optional: true
        secretName: ctl-secret
```
The mount is read-only and the mode is 292 (octal 444) which is read-only.

k8s seems to ignore this when setting file permissions, but does enforce no writing:
```
responsive-operator@responsive-operator-864897dd4-vvffr:/$ ls -l /etc/responsive-operator/
total 0
lrwxrwxrwx 1 root root 25 Jan 19 20:58 secrets.properties -> ..data/secrets.properties
responsive-operator@responsive-operator-864897dd4-vvffr:/$ echo foo > /etc/responsive-operator/secrets.properties
bash: /etc/responsive-operator/secrets.properties: Read-only file system
```
